"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppLayout } from "modules/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rage Trade",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        type: "image/svg+xml",
        url: "/icon.svg"
      }
    ]
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
